{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMXstmlnJqBPI6HXKwh1ZZv",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Akshita06-tech/Assignment_Akshita_00501222025/blob/main/ML1.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "DD-Z7Oyi3n6c"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "\n",
        "import numpy as np\n",
        "\n",
        "from sklearn.tree import DecisionTreeClassifier\n",
        "\n",
        "from sklearn.neighbors import KNeighborsClassifier\n",
        "\n",
        "from sklearn.linear_model import LinearRegression\n",
        "\n",
        "from sklearn.model_selection import train_test_split\n",
        "\n",
        "from sklearn.metrics import accuracy_score,confusion_matrix\n",
        "\n",
        "from sklearn.preprocessing import LabelEncode\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "yQotzpQe5LDz",
        "outputId": "b8a30963-0319-4ae1-d55e-fb31c12e999f"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "start code\n"
          ]
        }
      ],
      "source": [
        "print(\"start code\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# step 2 : load the dataset\n",
        "\n",
        "df = pd.read_csv('ShopSmart_Customers.csv')\n",
        "\n",
        "# display first 5 rows\n",
        "\n",
        "df.head()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 226
        },
        "id": "_9vm23Mu54n2",
        "outputId": "0e591147-c028-4099-dd29-d574af6300f3"
      },
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "   CustomerID  Age  Gender  Income  ProductsViewed  CartItems  TimeOnSite  \\\n",
              "0           1   20    Male   24114              39          7          19   \n",
              "1           2   57  Female   84965              40          5          37   \n",
              "2           3   51    Male   56321              17          9          39   \n",
              "3           4   57    Male   93297              37          2          21   \n",
              "4           5   44    Male  116652              39          2           8   \n",
              "\n",
              "   PreviousPurchases  DiscountUsed Membership FavoriteCategory  Purchased  \\\n",
              "0                 11            30     Silver            Books          1   \n",
              "1                 25             3     Silver            Books          1   \n",
              "2                  3            22   Platinum            Books          1   \n",
              "3                 25             1     Silver          Fashion          1   \n",
              "4                  7            21     Silver             Home          1   \n",
              "\n",
              "   AmountSpent  \n",
              "0         7514  \n",
              "1        10648  \n",
              "2         9002  \n",
              "3         8881  \n",
              "4         7116  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-4cfbe2a4-3cdd-4edd-85d6-48ef4cfa87a3\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>CustomerID</th>\n",
              "      <th>Age</th>\n",
              "      <th>Gender</th>\n",
              "      <th>Income</th>\n",
              "      <th>ProductsViewed</th>\n",
              "      <th>CartItems</th>\n",
              "      <th>TimeOnSite</th>\n",
              "      <th>PreviousPurchases</th>\n",
              "      <th>DiscountUsed</th>\n",
              "      <th>Membership</th>\n",
              "      <th>FavoriteCategory</th>\n",
              "      <th>Purchased</th>\n",
              "      <th>AmountSpent</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>20</td>\n",
              "      <td>Male</td>\n",
              "      <td>24114</td>\n",
              "      <td>39</td>\n",
              "      <td>7</td>\n",
              "      <td>19</td>\n",
              "      <td>11</td>\n",
              "      <td>30</td>\n",
              "      <td>Silver</td>\n",
              "      <td>Books</td>\n",
              "      <td>1</td>\n",
              "      <td>7514</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>57</td>\n",
              "      <td>Female</td>\n",
              "      <td>84965</td>\n",
              "      <td>40</td>\n",
              "      <td>5</td>\n",
              "      <td>37</td>\n",
              "      <td>25</td>\n",
              "      <td>3</td>\n",
              "      <td>Silver</td>\n",
              "      <td>Books</td>\n",
              "      <td>1</td>\n",
              "      <td>10648</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>51</td>\n",
              "      <td>Male</td>\n",
              "      <td>56321</td>\n",
              "      <td>17</td>\n",
              "      <td>9</td>\n",
              "      <td>39</td>\n",
              "      <td>3</td>\n",
              "      <td>22</td>\n",
              "      <td>Platinum</td>\n",
              "      <td>Books</td>\n",
              "      <td>1</td>\n",
              "      <td>9002</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>4</td>\n",
              "      <td>57</td>\n",
              "      <td>Male</td>\n",
              "      <td>93297</td>\n",
              "      <td>37</td>\n",
              "      <td>2</td>\n",
              "      <td>21</td>\n",
              "      <td>25</td>\n",
              "      <td>1</td>\n",
              "      <td>Silver</td>\n",
              "      <td>Fashion</td>\n",
              "      <td>1</td>\n",
              "      <td>8881</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>5</td>\n",
              "      <td>44</td>\n",
              "      <td>Male</td>\n",
              "      <td>116652</td>\n",
              "      <td>39</td>\n",
              "      <td>2</td>\n",
              "      <td>8</td>\n",
              "      <td>7</td>\n",
              "      <td>21</td>\n",
              "      <td>Silver</td>\n",
              "      <td>Home</td>\n",
              "      <td>1</td>\n",
              "      <td>7116</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-4cfbe2a4-3cdd-4edd-85d6-48ef4cfa87a3')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-4cfbe2a4-3cdd-4edd-85d6-48ef4cfa87a3 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-4cfbe2a4-3cdd-4edd-85d6-48ef4cfa87a3');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df",
              "summary": "{\n  \"name\": \"df\",\n  \"rows\": 500,\n  \"fields\": [\n    {\n      \"column\": \"CustomerID\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 144,\n        \"min\": 1,\n        \"max\": 500,\n        \"num_unique_values\": 500,\n        \"samples\": [\n          362,\n          74,\n          375\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 13,\n        \"min\": 18,\n        \"max\": 64,\n        \"num_unique_values\": 47,\n        \"samples\": [\n          19,\n          18,\n          35\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Gender\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"Female\",\n          \"Male\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Income\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 37710,\n        \"min\": 20207,\n        \"max\": 149992,\n        \"num_unique_values\": 498,\n        \"samples\": [\n          70331,\n          124874\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ProductsViewed\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 13,\n        \"min\": 1,\n        \"max\": 49,\n        \"num_unique_values\": 49,\n        \"samples\": [\n          5,\n          3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"CartItems\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2,\n        \"min\": 0,\n        \"max\": 9,\n        \"num_unique_values\": 10,\n        \"samples\": [\n          8,\n          5\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"TimeOnSite\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 16,\n        \"min\": 1,\n        \"max\": 59,\n        \"num_unique_values\": 59,\n        \"samples\": [\n          19,\n          28\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"PreviousPurchases\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 8,\n        \"min\": 0,\n        \"max\": 29,\n        \"num_unique_values\": 30,\n        \"samples\": [\n          29,\n          26\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"DiscountUsed\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 11,\n        \"min\": 0,\n        \"max\": 39,\n        \"num_unique_values\": 40,\n        \"samples\": [\n          5,\n          4\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Membership\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"Silver\",\n          \"Platinum\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"FavoriteCategory\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"Fashion\",\n          \"Electronics\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Purchased\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"AmountSpent\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3224,\n        \"min\": 0,\n        \"max\": 16326,\n        \"num_unique_values\": 465,\n        \"samples\": [\n          3690,\n          5276\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 3
        }
      ]
    },
    {
      "source": [
        "#step 3 : understand the dataset\n",
        "\n",
        "print('Shape:' , df.shape)\n",
        "\n",
        "print('\\nColumns:')\n",
        "\n",
        "print(df.columns)\n",
        "\n",
        "print('\\nData Types')\n",
        "\n",
        "print(df.dtypes)"
      ],
      "cell_type": "code",
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Shape: (500, 13)\n",
            "\n",
            "Columns:\n",
            "Index(['CustomerID', 'Age', 'Gender', 'Income', 'ProductsViewed', 'CartItems',\n",
            "       'TimeOnSite', 'PreviousPurchases', 'DiscountUsed', 'Membership',\n",
            "       'FavoriteCategory', 'Purchased', 'AmountSpent'],\n",
            "      dtype='object')\n",
            "\n",
            "Data Types\n",
            "CustomerID            int64\n",
            "Age                   int64\n",
            "Gender               object\n",
            "Income                int64\n",
            "ProductsViewed        int64\n",
            "CartItems             int64\n",
            "TimeOnSite            int64\n",
            "PreviousPurchases     int64\n",
            "DiscountUsed          int64\n",
            "Membership           object\n",
            "FavoriteCategory     object\n",
            "Purchased             int64\n",
            "AmountSpent           int64\n",
            "dtype: object\n"
          ]
        }
      ],
      "metadata": {
        "cellView": "form",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "lebANjkr571D",
        "outputId": "008bf413-e39b-4169-9dd4-5234c285687c"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# STEP\n",
        "df.describe()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 320
        },
        "id": "CThEwBGv6Cmc",
        "outputId": "3d1b5463-fb11-4d69-bbcd-d18c6b67acda"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "       CustomerID         Age         Income  ProductsViewed   CartItems  \\\n",
              "count  500.000000  500.000000     500.000000      500.000000  500.000000   \n",
              "mean   250.500000   41.428000   87556.388000       25.460000    4.356000   \n",
              "std    144.481833   13.569565   37710.299661       13.825291    2.824397   \n",
              "min      1.000000   18.000000   20207.000000        1.000000    0.000000   \n",
              "25%    125.750000   29.750000   54571.250000       14.000000    2.000000   \n",
              "50%    250.500000   42.000000   88597.500000       24.500000    4.000000   \n",
              "75%    375.250000   53.000000  120186.750000       37.000000    7.000000   \n",
              "max    500.000000   64.000000  149992.000000       49.000000    9.000000   \n",
              "\n",
              "       TimeOnSite  PreviousPurchases  DiscountUsed  Purchased   AmountSpent  \n",
              "count  500.000000         500.000000     500.00000  500.00000    500.000000  \n",
              "mean    29.830000          14.852000      19.06800    0.95800   8558.034000  \n",
              "std     16.651115           8.638712      11.55571    0.20079   3224.867606  \n",
              "min      1.000000           0.000000       0.00000    0.00000      0.000000  \n",
              "25%     16.000000           7.000000       9.00000    1.00000   6730.750000  \n",
              "50%     30.000000          15.000000      19.00000    1.00000   8779.500000  \n",
              "75%     44.000000          22.250000      28.25000    1.00000  10704.500000  \n",
              "max     59.000000          29.000000      39.00000    1.00000  16326.000000  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-c24889d5-a284-4fba-a255-706d5b5e4343\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>CustomerID</th>\n",
              "      <th>Age</th>\n",
              "      <th>Income</th>\n",
              "      <th>ProductsViewed</th>\n",
              "      <th>CartItems</th>\n",
              "      <th>TimeOnSite</th>\n",
              "      <th>PreviousPurchases</th>\n",
              "      <th>DiscountUsed</th>\n",
              "      <th>Purchased</th>\n",
              "      <th>AmountSpent</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>count</th>\n",
              "      <td>500.000000</td>\n",
              "      <td>500.000000</td>\n",
              "      <td>500.000000</td>\n",
              "      <td>500.000000</td>\n",
              "      <td>500.000000</td>\n",
              "      <td>500.000000</td>\n",
              "      <td>500.000000</td>\n",
              "      <td>500.00000</td>\n",
              "      <td>500.00000</td>\n",
              "      <td>500.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>mean</th>\n",
              "      <td>250.500000</td>\n",
              "      <td>41.428000</td>\n",
              "      <td>87556.388000</td>\n",
              "      <td>25.460000</td>\n",
              "      <td>4.356000</td>\n",
              "      <td>29.830000</td>\n",
              "      <td>14.852000</td>\n",
              "      <td>19.06800</td>\n",
              "      <td>0.95800</td>\n",
              "      <td>8558.034000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>std</th>\n",
              "      <td>144.481833</td>\n",
              "      <td>13.569565</td>\n",
              "      <td>37710.299661</td>\n",
              "      <td>13.825291</td>\n",
              "      <td>2.824397</td>\n",
              "      <td>16.651115</td>\n",
              "      <td>8.638712</td>\n",
              "      <td>11.55571</td>\n",
              "      <td>0.20079</td>\n",
              "      <td>3224.867606</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>min</th>\n",
              "      <td>1.000000</td>\n",
              "      <td>18.000000</td>\n",
              "      <td>20207.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.00000</td>\n",
              "      <td>0.00000</td>\n",
              "      <td>0.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>25%</th>\n",
              "      <td>125.750000</td>\n",
              "      <td>29.750000</td>\n",
              "      <td>54571.250000</td>\n",
              "      <td>14.000000</td>\n",
              "      <td>2.000000</td>\n",
              "      <td>16.000000</td>\n",
              "      <td>7.000000</td>\n",
              "      <td>9.00000</td>\n",
              "      <td>1.00000</td>\n",
              "      <td>6730.750000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>50%</th>\n",
              "      <td>250.500000</td>\n",
              "      <td>42.000000</td>\n",
              "      <td>88597.500000</td>\n",
              "      <td>24.500000</td>\n",
              "      <td>4.000000</td>\n",
              "      <td>30.000000</td>\n",
              "      <td>15.000000</td>\n",
              "      <td>19.00000</td>\n",
              "      <td>1.00000</td>\n",
              "      <td>8779.500000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>75%</th>\n",
              "      <td>375.250000</td>\n",
              "      <td>53.000000</td>\n",
              "      <td>120186.750000</td>\n",
              "      <td>37.000000</td>\n",
              "      <td>7.000000</td>\n",
              "      <td>44.000000</td>\n",
              "      <td>22.250000</td>\n",
              "      <td>28.25000</td>\n",
              "      <td>1.00000</td>\n",
              "      <td>10704.500000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>max</th>\n",
              "      <td>500.000000</td>\n",
              "      <td>64.000000</td>\n",
              "      <td>149992.000000</td>\n",
              "      <td>49.000000</td>\n",
              "      <td>9.000000</td>\n",
              "      <td>59.000000</td>\n",
              "      <td>29.000000</td>\n",
              "      <td>39.00000</td>\n",
              "      <td>1.00000</td>\n",
              "      <td>16326.000000</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-c24889d5-a284-4fba-a255-706d5b5e4343')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-c24889d5-a284-4fba-a255-706d5b5e4343 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-c24889d5-a284-4fba-a255-706d5b5e4343');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"df\",\n  \"rows\": 8,\n  \"fields\": [\n    {\n      \"column\": \"CustomerID\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 179.8977277873755,\n        \"min\": 1.0,\n        \"max\": 500.0,\n        \"num_unique_values\": 6,\n        \"samples\": [\n          500.0,\n          250.5,\n          375.25\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 164.4236930065202,\n        \"min\": 13.56956455323193,\n        \"max\": 500.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          41.428,\n          42.0,\n          500.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Income\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 50936.55722098947,\n        \"min\": 500.0,\n        \"max\": 149992.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          87556.388,\n          88597.5,\n          500.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ProductsViewed\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 169.1002090263663,\n        \"min\": 1.0,\n        \"max\": 500.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          25.46,\n          24.5,\n          500.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"CartItems\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 175.32539763160275,\n        \"min\": 0.0,\n        \"max\": 500.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          4.356,\n          4.0,\n          500.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"TimeOnSite\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 167.80317791790455,\n        \"min\": 1.0,\n        \"max\": 500.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          29.83,\n          30.0,\n          500.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"PreviousPurchases\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 172.12654690075794,\n        \"min\": 0.0,\n        \"max\": 500.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          14.852,\n          15.0,\n          500.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"DiscountUsed\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 170.83552987923719,\n        \"min\": 0.0,\n        \"max\": 500.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          19.068,\n          19.0,\n          500.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Purchased\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 176.51660492043865,\n        \"min\": 0.0,\n        \"max\": 500.0,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          0.958,\n          1.0,\n          0.20079002282616804\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"AmountSpent\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 5499.257510379592,\n        \"min\": 0.0,\n        \"max\": 16326.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          8558.034,\n          8779.5,\n          500.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 6
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# STEP 5: BUSINESS QUESTIONS\n",
        "\n",
        "# Total customers\n",
        "print('Customers:', len(df))\n",
        "\n",
        "# Total purchasers\n",
        "print('Purchased:', df['Purchased'].sum())\n",
        "\n",
        "# Average spending\n",
        "print('Average Spending:', round(df['AmountSpent'].mean(), 2))\n",
        "\n",
        "# Highest spender\n",
        "print('\\nHighest Spender')\n",
        "print(df.loc[df['AmountSpent'].idxmax()])"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "M6mTmwEi6QyS",
        "outputId": "99cab8a9-3922-4c64-91ad-b065fdc00794"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Customers: 500\n",
            "Purchased: 479\n",
            "Average Spending: 8558.03\n",
            "\n",
            "Highest Spender\n",
            "CustomerID              281\n",
            "Age                      62\n",
            "Gender               Female\n",
            "Income               145654\n",
            "ProductsViewed            4\n",
            "CartItems                 9\n",
            "TimeOnSite                9\n",
            "PreviousPurchases        28\n",
            "DiscountUsed              9\n",
            "Membership             Gold\n",
            "FavoriteCategory      Books\n",
            "Purchased                 1\n",
            "AmountSpent           16326\n",
            "Name: 280, dtype: object\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# STEP 6: PREPARE DATA\n",
        "\n",
        "# Machine learning algorithms require numbers.\n",
        "# Membership and FavoriteCategory contain text.\n",
        "\n",
        "le = LabelEncoder()\n",
        "\n",
        "df['Gender'] = le.fit_transform(df['Gender'])\n",
        "df['Membership'] = le.fit_transform(df['Membership'])\n",
        "df['FavoriteCategory'] = le.fit_transform(df['FavoriteCategory'])"
      ],
      "metadata": {
        "id": "qe8njIvB8SZy"
      },
      "execution_count": 15,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# STEP 7\n",
        "\n",
        "#Business Question: will customer purchase ?\n",
        "\n",
        "X = df.drop(['CustomerID', 'Purchased', 'AmountSpent'], axis=1)\n",
        "\n",
        "y = df['Purchased']\n",
        "\n",
        "\n",
        "\n",
        "X_train, X_test, y_train, y_test = train_test_split(\n",
        "\n",
        "    X, y, test_size=0.2, random_state=42\n",
        "\n",
        ")\n",
        "\n",
        "\n",
        "\n",
        "dt = DecisionTreeClassifier(random_state=42)\n",
        "\n",
        "dt.fit(X_train, y_train)\n",
        "\n",
        "pred = dt.predict(X_test)\n",
        "print('Decision Tree Accuracy:', accuracy_score(y_test, pred))\n",
        "\n",
        "print('\\nConfusion Matrix')\n",
        "print(confusion_matrix(y_test, pred))\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "3jri2MaF9tmh",
        "outputId": "98add720-6dc0-48d9-8c9d-1af996aa2928"
      },
      "execution_count": 18,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Decision Tree Accuracy: 0.96\n",
            "\n",
            "Confusion Matrix\n",
            "[[ 3  2]\n",
            " [ 2 93]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Predict purchase for a new customer\n",
        "\n",
        "new_customer = [[30, 1, 60000, 20, 3, 15, 5, 10, 1, 2]]\n",
        "\n",
        "print('Purchase Prediction:', dt.predict(new_customer)[0])"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "imW22R4qCSrf",
        "outputId": "6eaec9b4-9239-43be-f6ca-befbb8d91503"
      },
      "execution_count": 21,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Purchase Prediction: 1\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names\n",
            "  warnings.warn(\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# STEP 8 : KNN\n",
        "\n",
        "knn = KNeighborsClassifier(n_neighbors=5)\n",
        "\n",
        "knn.fit(X_train, y_train)\n",
        "\n",
        "pred = knn.predict(X_test)\n",
        "\n",
        "print('KNN Accuracy:', accuracy_score(y_test, pred))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "DJSSjSjrDhgZ",
        "outputId": "8167d207-b3b1-4966-8e15-75f63fe65cad"
      },
      "execution_count": 22,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "KNN Accuracy: 0.95\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# STEP 9 : LINEAR REGRESSION\n",
        "\n",
        "X_reg = df.drop(['CustomerID', 'Purchased', 'AmountSpent'], axis=1)\n",
        "\n",
        "y_reg = df['AmountSpent']\n",
        "\n",
        "X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(\n",
        "\n",
        "    X_reg, y_reg, test_size=0.2, random_state=42\n",
        "\n",
        ")\n",
        "\n",
        "lr = LinearRegression()\n",
        "\n",
        "lr.fit(X_train_reg, y_train_reg)\n",
        "\n",
        "amount = lr.predict([[30, 1, 60000, 20, 3, 15, 5, 10, 1, 2]])\n",
        "\n",
        "print('predicted Spending:', amount[0])"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "DHHjoBLZD6sL",
        "outputId": "b0dea715-83f9-4c11-c53e-46933976fdb7"
      },
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "predicted Spending: 4477.686668606446\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names\n",
            "  warnings.warn(\n"
          ]
        }
      ]
    }
  ]
}